services:
  server:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
